apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-prvi-deployment
spec:
  replicas: 3

  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 2
  #     maxSurge: 2

  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: treningapp
        image: vlajko83/treningapp:v2
        imagePullPolicy: Always
        # - name: WELCOME_MSG         
        #   valueFrom:
        #     config_map_key_ref:
        #       name: moj-prvi-config
        #       key: WELCOME_MSG
        # - name: APP_COLOR          
        #   valueFrom:
        #     config_map_key_ref:
        #       name: moj-prvi-config
        #       key: APP_COLOR
        # - name: APP_VERSION       
        #   valueFrom:
        #     config_map_key_ref:
        #       name: moj-prvi-config
        #       key: APP_VERSION
        ports:
        - containerPort: 5000