apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 5000