apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-prvi-deployment
spec:
  replicas: 3

  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 2
  #     maxSurge: 2

  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: treningapp
        image: vlajko83/treningapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000