apiVersion: v1
kind: Service
metadata:
  name: moj-prvi-service
spec:
  type: NodePort
  selector:
    app: training
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080