apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trening-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: trening.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moj-prvi-service
            port:
              number: 80